"use client";

import { useLocale, useTranslations } from "next-intl";

import { toLocale, type Locale } from "@/lib/i18n/config";
import { formatDateTime as formatLocalizedDateTime } from "@/lib/models/formatDateTime";

import { useCallback, useEffect, useMemo, useState } from "react";

import type { ManagementRole } from "@/types/model";

type NotesTabProps = {
    modelId: string;
    currentUserRole: ManagementRole;
    historyOnly?: boolean;
};

type NotePriority =
    | "normal"
    | "important"
    | "urgent";

type ModelNote = {
    id: string;
    modelId: string;
    body: string;
    priority: NotePriority;
    pinned: boolean;
    archived: boolean;
    deletedAt: string | null;
    deletedByName: string | null;
    createdContext: string | null;
    /** 'ledger' notes are generated by an expense or loan entry. */
    source: "manual" | "ledger";
    createdByName: string;
    createdByRole: string;
    updatedByName: string | null;
    updatedByRole: string | null;
    previousRepresentativeId?: string | null;
    newRepresentativeId?: string | null;
    createdAt: string;
    updatedAt: string;
};

type NoteHistory = {
    id: string;
    noteId: string | null;
    action: string;
    fieldName: string | null;
    summary: string | null;
    originalBody: string | null;
    updatedBody: string | null;
    editorName: string;
    editorRole: string;
    createdAt: string;
};

type ApiPermissions = {
    canCreate?: boolean;
    canEdit?: boolean;
    canPin?: boolean;
    canArchive?: boolean;
    canSoftDelete?: boolean;
    canPurge?: boolean;
};

type NotesApiResponse = {
    notes?: unknown[];
    history?: unknown[];
    recentHistory?: unknown[];
    permissions?: ApiPermissions;
    error?: string;
};

/** The value is the stored priority; the word comes from `enums.notePriority`. */
const priorityOptions: NotePriority[] = ["normal", "important", "urgent"];

export default function NotesTab({
    modelId,
    currentUserRole,
    historyOnly = false,
}: NotesTabProps) {
    const t = useTranslations("admin.notes");
    const tCommon = useTranslations("common.actions");
    const tPriority = useTranslations("enums.notePriority");
    const locale = toLocale(useLocale());

    const unknownUser = t("unknownUser");

    const [notes, setNotes] = useState<ModelNote[]>([]);
    const [history, setHistory] = useState<NoteHistory[]>([]);

    const [permissions, setPermissions] =
        useState<ApiPermissions>({});

    const [newNoteBody, setNewNoteBody] =
        useState("");

    const [newNotePriority, setNewNotePriority] =
        useState<NotePriority>("normal");

    const [editingNote, setEditingNote] =
        useState<ModelNote | null>(null);

    const [editingBody, setEditingBody] =
        useState("");

    const [editingPriority, setEditingPriority] =
        useState<NotePriority>("normal");

    const [showArchived, setShowArchived] =
        useState(false);

    const [isLoading, setIsLoading] =
        useState(true);

    const [isSaving, setIsSaving] =
        useState(false);

    const [actionNoteId, setActionNoteId] =
        useState<string | null>(null);

    const [errorMessage, setErrorMessage] =
        useState<string | null>(null);

    const [successMessage, setSuccessMessage] =
        useState<string | null>(null);

    // The note waiting on the confirmation modal, and which kind of removal it
    // is waiting for. window.confirm / window.prompt used to stand here, and on
    // a phone those are dialogs the browser is free to suppress — when it does,
    // they return null and the click silently does nothing, which is exactly
    // how "the Excluir button does not delete" looks.
    const [pendingRemoval, setPendingRemoval] = useState<{
        note: ModelNote;
        kind: "soft" | "purge";
    } | null>(null);

    const isOwner =
        currentUserRole === "owner";

    const canCreate =
        permissions.canCreate ??
        (currentUserRole === "owner" ||
            currentUserRole === "administrator");

    const canEdit =
        permissions.canEdit ?? isOwner;

    const canPin =
        permissions.canPin ??
        (currentUserRole === "owner" ||
            currentUserRole === "administrator");

    const canArchive =
        permissions.canArchive ??
        (currentUserRole === "owner" ||
            currentUserRole === "administrator");

    // Soft delete (Excluir) and permanent purge are owner-only.
    const canSoftDelete =
        permissions.canSoftDelete ?? isOwner;
    const canPurge =
        permissions.canPurge ?? isOwner;

    const loadNotes = useCallback(async () => {
        setIsLoading(true);
        setErrorMessage(null);

        try {
            const response = await fetch(
                `/api/models/notes?modelId=${encodeURIComponent(
                    modelId,
                )}`,
                {
                    method: "GET",
                    cache: "no-store",
                },
            );

            const result =
                (await response.json()) as NotesApiResponse;

            if (!response.ok) {
                throw new Error(
                    result.error ??
                        t("loadFailed"),
                );
            }

            const rawNotes = Array.isArray(result.notes)
                ? result.notes
                : [];

            const rawHistory = Array.isArray(
                result.recentHistory,
            )
                ? result.recentHistory
                : Array.isArray(result.history)
                  ? result.history
                  : [];

            setNotes(
                rawNotes
                    .map((raw) => normalizeNote(raw, unknownUser))
                    .filter(
                        (
                            note,
                        ): note is ModelNote =>
                            note !== null,
                    ),
            );

            setHistory(
                rawHistory
                    .map((raw) => normalizeHistory(raw, unknownUser))
                    .filter(
                        (
                            item,
                        ): item is NoteHistory =>
                            item !== null,
                    ),
            );

            setPermissions(
                result.permissions ?? {},
            );
        } catch (error) {
            setErrorMessage(
                error instanceof Error
                    ? error.message
                    : t("loadFailed"),
            );
        } finally {
            setIsLoading(false);
        }
    }, [modelId]);

    useEffect(() => {
        void loadNotes();
    }, [loadNotes]);

    const visibleNotes = useMemo(() => {
        return notes
            .filter(
                (note) =>
                    showArchived || !note.archived,
            )
            .sort((first, second) => {
                if (
                    first.pinned !== second.pinned
                ) {
                    return first.pinned ? -1 : 1;
                }

                return (
                    new Date(
                        second.updatedAt,
                    ).getTime() -
                    new Date(
                        first.updatedAt,
                    ).getTime()
                );
            });
    }, [notes, showArchived]);

    const recentHistory = useMemo(() => {
        return [...history].sort(
            (first, second) =>
                new Date(
                    second.createdAt,
                ).getTime() -
                new Date(
                    first.createdAt,
                ).getTime(),
        );
    }, [history]);

    async function createNote() {
        const body = newNoteBody.trim();

        if (!canCreate || isSaving) {
            return;
        }

        if (!body) {
            setErrorMessage(
                t("emptyNote"),
            );
            return;
        }

        setIsSaving(true);
        setErrorMessage(null);

        try {
            const response = await fetch(
                "/api/models/notes",
                {
                    method: "POST",
                    headers: {
                        "Content-Type":
                            "application/json",
                    },
                    body: JSON.stringify({
                        modelId,
                        body,
                        priority:
                            newNotePriority,
                    }),
                },
            );

            const result =
                (await response.json()) as {
                    note?: unknown;
                    error?: string;
                };

            if (!response.ok) {
                throw new Error(
                    result.error ??
                        t("addFailed"),
                );
            }

            setNewNoteBody("");
            setNewNotePriority("normal");

            await loadNotes();
        } catch (error) {
            setErrorMessage(
                error instanceof Error
                    ? error.message
                    : t("addFailed"),
            );
        } finally {
            setIsSaving(false);
        }
    }

    function beginEditing(note: ModelNote) {
        if (!canEdit) {
            return;
        }

        setEditingNote(note);
        setEditingBody(note.body);
        setEditingPriority(note.priority);
        setErrorMessage(null);
    }

    function cancelEditing() {
        if (isSaving) {
            return;
        }

        setEditingNote(null);
        setEditingBody("");
        setEditingPriority("normal");
    }

    async function confirmEdit() {
        if (
            !editingNote ||
            !canEdit ||
            isSaving
        ) {
            return;
        }

        const body = editingBody.trim();

        if (!body) {
            setErrorMessage(
                t("emptyNote"),
            );
            return;
        }

        setIsSaving(true);
        setErrorMessage(null);

        try {
            const response = await fetch(
                "/api/models/notes",
                {
                    method: "PATCH",
                    headers: {
                        "Content-Type":
                            "application/json",
                    },
                    body: JSON.stringify({
                        modelId,
                        noteId: editingNote.id,
                        action: "edit",
                        body,
                        priority:
                            editingPriority,
                    }),
                },
            );

            const result =
                (await response.json()) as {
                    error?: string;
                };

            if (!response.ok) {
                throw new Error(
                    result.error ??
                        t("editFailed"),
                );
            }

            setEditingNote(null);
            setEditingBody("");
            setEditingPriority("normal");

            await loadNotes();
        } catch (error) {
            setErrorMessage(
                error instanceof Error
                    ? error.message
                    : t("editFailed"),
            );
        } finally {
            setIsSaving(false);
        }
    }

    async function togglePinned(
        note: ModelNote,
    ) {
        if (!canPin || actionNoteId) {
            return;
        }

        setActionNoteId(note.id);
        setErrorMessage(null);

        try {
            const response = await fetch(
                "/api/models/notes",
                {
                    method: "PATCH",
                    headers: {
                        "Content-Type":
                            "application/json",
                    },
                    body: JSON.stringify({
                        modelId,
                        noteId: note.id,
                        action: "pin",
                        pinned: !note.pinned,
                    }),
                },
            );

            const result =
                (await response.json()) as {
                    error?: string;
                };

            if (!response.ok) {
                throw new Error(
                    result.error ??
                        t("pinFailed"),
                );
            }

            await loadNotes();
        } catch (error) {
            setErrorMessage(
                error instanceof Error
                    ? error.message
                    : t("updateFailed"),
            );
        } finally {
            setActionNoteId(null);
        }
    }

    async function toggleArchived(
        note: ModelNote,
    ) {
        if (!canArchive || actionNoteId) {
            return;
        }

        setActionNoteId(note.id);
        setErrorMessage(null);

        try {
            const response = await fetch(
                "/api/models/notes",
                {
                    method: "PATCH",
                    headers: {
                        "Content-Type":
                            "application/json",
                    },
                    body: JSON.stringify({
                        modelId,
                        noteId: note.id,
                        action: "archive",
                        archived:
                            !note.archived,
                    }),
                },
            );

            const result =
                (await response.json()) as {
                    error?: string;
                };

            if (!response.ok) {
                throw new Error(
                    result.error ??
                        t("archiveFailed"),
                );
            }

            await loadNotes();
        } catch (error) {
            setErrorMessage(
                error instanceof Error
                    ? error.message
                    : t("updateFailed"),
            );
        } finally {
            setActionNoteId(null);
        }
    }

    function requestRemoval(
        note: ModelNote,
        kind: "soft" | "purge",
    ) {
        if (actionNoteId) {
            return;
        }

        if (kind === "soft" ? !canSoftDelete : !canPurge) {
            return;
        }

        setErrorMessage(null);
        setSuccessMessage(null);
        setPendingRemoval({ note, kind });
    }

    async function softDeleteNote(
        note: ModelNote,
    ) {
        if (!canSoftDelete || actionNoteId) {
            return;
        }

        setActionNoteId(note.id);
        setErrorMessage(null);

        try {
            const response = await fetch(
                "/api/models/notes",
                {
                    method: "PATCH",
                    headers: {
                        "Content-Type":
                            "application/json",
                    },
                    body: JSON.stringify({
                        modelId,
                        noteId: note.id,
                        action: "soft-delete",
                    }),
                },
            );

            const result =
                (await response.json()) as {
                    error?: string;
                };

            if (!response.ok) {
                throw new Error(
                    result.error ??
                        t("deleteFailed"),
                );
            }

            setPendingRemoval(null);
            setSuccessMessage(
                t("deletedSoft"),
            );

            await loadNotes();
        } catch (error) {
            setErrorMessage(
                error instanceof Error
                    ? error.message
                    : t("deleteFailed"),
            );
        } finally {
            setActionNoteId(null);
        }
    }

    async function purgeNote(
        note: ModelNote,
    ) {
        if (!canPurge || actionNoteId) {
            return;
        }

        setActionNoteId(note.id);
        setErrorMessage(null);

        try {
            const response = await fetch(
                "/api/models/notes",
                {
                    method: "DELETE",
                    headers: {
                        "Content-Type":
                            "application/json",
                    },
                    body: JSON.stringify({
                        modelId,
                        noteId: note.id,
                    }),
                },
            );

            const result =
                (await response.json()) as {
                    error?: string;
                };

            if (!response.ok) {
                throw new Error(
                    result.error ??
                        t("hardDeleteFailed"),
                );
            }

            setPendingRemoval(null);
            setSuccessMessage(
                note.source === "ledger"
                    ? t("deletedHardWithEntry")
                    : t("deletedHard"),
            );

            await loadNotes();
        } catch (error) {
            setErrorMessage(
                error instanceof Error
                    ? error.message
                    : t("hardDeleteFailed"),
            );
        } finally {
            setActionNoteId(null);
        }
    }

    if (isLoading) {
        return (
            <LoadingSection
                historyOnly={historyOnly}
            />
        );
    }

    if (historyOnly) {
        return (
            <HistoryPanel
                history={recentHistory}
                errorMessage={errorMessage}
                fullWidth
            />
        );
    }

    return (
        <>
            {errorMessage && (
                <div className="mb-5 rounded-2xl border border-red-400/30 bg-red-500/10 px-5 py-4 text-sm text-red-200">
                    {errorMessage}
                </div>
            )}

            {successMessage && (
                <div className="mb-5 rounded-2xl border border-emerald-400/30 bg-emerald-500/10 px-5 py-4 text-sm text-emerald-200">
                    {successMessage}
                </div>
            )}

            <div className="grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(340px,0.8fr)]">
                <section className="rounded-2xl border border-white/10 bg-black/20 p-5 sm:p-6">
                    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                        <div>
                            <p className="text-xs font-bold uppercase tracking-[0.2em] text-pink-300">
                                {t("internalNotes")}
                            </p>

                            <h2 className="mt-2 text-2xl font-bold">
                                {t("notes")}
                            </h2>

                            <p className="mt-2 max-w-2xl text-sm leading-6 text-white/50">
                                {t("intro")}
                            </p>
                        </div>

                        <label className="inline-flex cursor-pointer items-center gap-3 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white/65">
                            <input
                                type="checkbox"
                                checked={showArchived}
                                onChange={(event) =>
                                    setShowArchived(
                                        event.target
                                            .checked,
                                    )
                                }
                                className="h-4 w-4 accent-pink-500"
                            />

                            {t("showArchived")}
                        </label>
                    </div>

                    {canCreate ? (
                        <div className="mt-6 rounded-2xl border border-pink-400/20 bg-pink-500/5 p-4 sm:p-5">
                            <label className="block">
                                <span className="text-xs font-bold uppercase tracking-[0.16em] text-white/45">
                                    {t("newNote")}
                                </span>

                                <textarea
                                    value={newNoteBody}
                                    onChange={(
                                        event,
                                    ) =>
                                        setNewNoteBody(
                                            event.target
                                                .value,
                                        )
                                    }
                                    rows={5}
                                    maxLength={5000}
                                    placeholder={t("notePlaceholder")}
                                    className="mt-3 w-full resize-y rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm leading-6 text-white outline-none transition placeholder:text-white/25 focus:border-pink-400/60"
                                />
                            </label>

                            <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
                                <label className="block">
                                    <span className="text-xs font-bold uppercase tracking-[0.16em] text-white/45">
                                        {t("priority")}
                                    </span>

                                    <select
                                        value={
                                            newNotePriority
                                        }
                                        onChange={(
                                            event,
                                        ) =>
                                            setNewNotePriority(
                                                event
                                                    .target
                                                    .value as NotePriority,
                                            )
                                        }
                                        className="mt-2 w-full min-w-[180px] rounded-xl border border-white/10 bg-[#111115] px-4 py-3 text-sm text-white outline-none focus:border-pink-400/60"
                                    >
                                        {priorityOptions.map((option) => (
                                                <option key={option} value={option}>
                                                    {tPriority(option)}
                                                </option>
                                            ))}
                                    </select>
                                </label>

                                <button
                                    type="button"
                                    onClick={() =>
                                        void createNote()
                                    }
                                    disabled={
                                        isSaving ||
                                        !newNoteBody.trim()
                                    }
                                    className="rounded-xl bg-pink-500 px-5 py-3 text-sm font-bold text-white transition hover:bg-pink-400 disabled:cursor-not-allowed disabled:opacity-40"
                                >
                                    {isSaving
                                        ? tCommon("saving")
                                        : t("addNote")}
                                </button>
                            </div>

                            <p className="mt-3 text-right text-xs text-white/35">
                                {newNoteBody.length} /
                                5000
                            </p>
                        </div>
                    ) : (
                        <div className="mt-6 rounded-2xl border border-white/10 bg-white/5 px-5 py-4 text-sm text-white/50">
                            {t("readOnlyNotice")}
                        </div>
                    )}

                    <div className="mt-6 space-y-4">
                        {visibleNotes.length === 0 ? (
                            <EmptyNotes
                                showArchived={
                                    showArchived
                                }
                            />
                        ) : (
                            visibleNotes.map(
                                (note) => (
                                    <NoteCard
                                        key={note.id}
                                        note={note}
                                        canEdit={
                                            canEdit
                                        }
                                        canPin={
                                            canPin
                                        }
                                        canArchive={
                                            canArchive
                                        }
                                        canSoftDelete={
                                            canSoftDelete
                                        }
                                        canPurge={
                                            canPurge
                                        }
                                        isActing={
                                            actionNoteId ===
                                            note.id
                                        }
                                        onEdit={() =>
                                            beginEditing(
                                                note,
                                            )
                                        }
                                        onTogglePin={() =>
                                            void togglePinned(
                                                note,
                                            )
                                        }
                                        onToggleArchive={() =>
                                            void toggleArchived(
                                                note,
                                            )
                                        }
                                        onSoftDelete={() =>
                                            requestRemoval(
                                                note,
                                                "soft",
                                            )
                                        }
                                        onPurge={() =>
                                            requestRemoval(
                                                note,
                                                "purge",
                                            )
                                        }
                                    />
                                ),
                            )
                        )}
                    </div>
                </section>

                <HistoryPanel
                    history={recentHistory}
                    errorMessage={null}
                />
            </div>

            {editingNote && (
                <EditConfirmationModal
                    note={editingNote}
                    body={editingBody}
                    priority={
                        editingPriority
                    }
                    isSaving={isSaving}
                    onBodyChange={
                        setEditingBody
                    }
                    onPriorityChange={
                        setEditingPriority
                    }
                    onCancel={
                        cancelEditing
                    }
                    onConfirm={() =>
                        void confirmEdit()
                    }
                />
            )}

            {pendingRemoval && (
                <RemoveNoteModal
                    note={pendingRemoval.note}
                    kind={pendingRemoval.kind}
                    isWorking={
                        actionNoteId ===
                        pendingRemoval.note.id
                    }
                    onCancel={() =>
                        setPendingRemoval(null)
                    }
                    onConfirm={() => {
                        if (
                            pendingRemoval.kind ===
                            "soft"
                        ) {
                            void softDeleteNote(
                                pendingRemoval.note,
                            );
                            return;
                        }

                        void purgeNote(
                            pendingRemoval.note,
                        );
                    }}
                />
            )}
        </>
    );
}

/**
 * Removal asks in the page, not through window.confirm / window.prompt: those
 * are dialogs a browser may suppress — notably mobile in-app browsers — and a
 * suppressed dialog returns nothing, so the button appears to do nothing at
 * all. That is what "the Excluir button does not delete the note" was.
 */
function RemoveNoteModal({
    note,
    kind,
    isWorking,
    onCancel,
    onConfirm,
}: {
    note: ModelNote;
    kind: "soft" | "purge";
    isWorking: boolean;
    onCancel: () => void;
    onConfirm: () => void;
}) {
    const t = useTranslations("admin.notes");
    const tCommon = useTranslations("common.actions");
    const locale = toLocale(useLocale());

    const isPurge = kind === "purge";

    return (
        <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-4 sm:items-center">
            <div
                role="dialog"
                aria-modal="true"
                aria-labelledby="remove-note-title"
                className="w-full max-w-lg rounded-2xl border border-red-400/30 bg-[#141118] p-6"
            >
                <h2
                    id="remove-note-title"
                    className="text-lg font-bold text-white"
                >
                    {isPurge
                        ? t("hardDeleteTitle")
                        : t("softDeleteTitle")}
                </h2>

                <div className="mt-4 space-y-3 text-sm leading-6 text-white/70">
                    <p>
                        {isPurge
                            ? t("hardDeleteBody")
                            : t("softDeleteBody")}
                    </p>

                    {note.source === "ledger" && isPurge && (
                        <p className="rounded-xl border border-amber-400/30 bg-amber-500/10 p-3 text-amber-200">
                            {t("ledgerDeleteWarning")}
                        </p>
                    )}

                    <blockquote className="max-h-40 overflow-y-auto rounded-xl border border-white/10 bg-black/30 p-3 text-xs italic text-white/60">
                        {note.body}
                    </blockquote>
                </div>

                <div className="mt-6 flex flex-wrap justify-end gap-3">
                    <button
                        type="button"
                        onClick={onCancel}
                        disabled={isWorking}
                        className="rounded-xl border border-white/15 px-5 py-3 text-xs font-bold uppercase tracking-wider text-white/70 transition hover:bg-white/10 disabled:opacity-50"
                    >
                        {tCommon("cancel")}
                    </button>

                    <button
                        type="button"
                        onClick={onConfirm}
                        disabled={isWorking}
                        className="rounded-xl bg-red-500 px-5 py-3 text-xs font-bold uppercase tracking-wider text-white transition hover:bg-red-400 disabled:opacity-50"
                    >
                        {isWorking
                            ? tCommon("deleting")
                            : isPurge
                              ? t("deleteForever")
                              : t("deleteNote")}
                    </button>
                </div>
            </div>
        </div>
    );
}

function NoteCard({
    note,
    canEdit,
    canPin,
    canArchive,
    canSoftDelete,
    canPurge,
    isActing,
    onEdit,
    onTogglePin,
    onToggleArchive,
    onSoftDelete,
    onPurge,
}: {
    note: ModelNote;
    canEdit: boolean;
    canPin: boolean;
    canArchive: boolean;
    canSoftDelete: boolean;
    canPurge: boolean;
    isActing: boolean;
    onEdit: () => void;
    onTogglePin: () => void;
    onToggleArchive: () => void;
    onSoftDelete: () => void;
    onPurge: () => void;
}) {
    const t = useTranslations("admin.notes");
    const tCommon = useTranslations("common.actions");
    const tPriority = useTranslations("enums.notePriority");
    const tRole = useTranslations("enums.role");
    const locale = toLocale(useLocale());

    const priority =
        priorityConfig(note.priority);

    return (
        <article
            className={`rounded-2xl border p-5 transition ${
                note.archived
                    ? "border-white/10 bg-white/[0.025] opacity-60"
                    : note.pinned
                      ? "border-pink-400/35 bg-pink-500/[0.08]"
                      : "border-white/10 bg-[#111115]"
            }`}
        >
            <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                <div className="flex flex-wrap items-center gap-2">
                    {note.pinned && (
                        <span className="rounded-full border border-pink-400/30 bg-pink-500/15 px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-pink-200">
                            {t("pinned")}
                        </span>
                    )}

                    {note.archived && (
                        <span className="rounded-full border border-white/15 bg-white/5 px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-white/50">
                            {t("archived")}
                        </span>
                    )}

                    <span
                        className={`rounded-full border px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] ${priority.className}`}
                    >
                        {tPriority(note.priority)}
                    </span>

                    {note.source === "ledger" && (
                        <span className="rounded-full border border-emerald-400/30 bg-emerald-500/10 px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-emerald-200">
                            {t("entry")}
                        </span>
                    )}
                </div>

                <div className="flex flex-wrap gap-2">
                    {canPin && (
                        <ActionButton
                            disabled={isActing}
                            onClick={onTogglePin}
                        >
                            {note.pinned
                                ? "Desafixar"
                                : "Fixar"}
                        </ActionButton>
                    )}

                    {canEdit &&
                        !note.archived && (
                            <ActionButton
                                disabled={
                                    isActing
                                }
                                onClick={
                                    onEdit
                                }
                            >
                                {tCommon("edit")}
                            </ActionButton>
                        )}

                    {canArchive && (
                        <ActionButton
                            disabled={isActing}
                            onClick={
                                onToggleArchive
                            }
                        >
                            {note.archived
                                ? t("restore")
                                : t("archive")}
                        </ActionButton>
                    )}

                    {canSoftDelete &&
                        !note.deletedAt && (
                            <button
                                type="button"
                                disabled={isActing}
                                onClick={onSoftDelete}
                                className="rounded-xl border border-red-400/30 px-4 py-2 text-xs font-bold text-red-200 transition hover:bg-red-500/10 disabled:opacity-40"
                            >
                                {tCommon("delete")}
                            </button>
                        )}

                    {canPurge && note.deletedAt && (
                        <button
                            type="button"
                            disabled={isActing}
                            onClick={onPurge}
                            className="rounded-xl border border-red-600/40 bg-red-500/10 px-4 py-2 text-xs font-bold text-red-300 transition hover:bg-red-500/20 disabled:opacity-40"
                        >
                            {t("deletePermanently")}
                        </button>
                    )}
                </div>
            </div>

            <p className="mt-4 whitespace-pre-wrap break-words text-sm leading-7 text-white/85">
                {note.body}
            </p>

            <div className="mt-5 border-t border-white/10 pt-4 text-xs text-white/40">
                <p>
                    Criada por{" "}
                    <span className="font-semibold text-white/65">
                        {note.createdByName}
                    </span>{" "}
                    ·{" "}
                    {tRole(note.createdByRole)}{" "}
                    ·{" "}
                    {formatDateTime(note.createdAt, locale)}
                </p>

                {note.updatedAt !==
                    note.createdAt && (
                    <p className="mt-1">
                        Última edição por{" "}
                        <span className="font-semibold text-white/65">
                            {note.updatedByName ??
                                note.createdByName}
                        </span>{" "}
                        ·{" "}
                        {tRole(
                            note.updatedByRole ??
                                note.createdByRole,
                        )}{" "}
                        ·{" "}
                        {formatDateTime(note.updatedAt, locale)}
                    </p>
                )}
            </div>
        </article>
    );
}

function HistoryPanel({
    history,
    errorMessage,
    fullWidth = false,
}: {
    history: NoteHistory[];
    errorMessage: string | null;
    fullWidth?: boolean;
}) {
    const t = useTranslations("admin.notes");
    const locale = toLocale(useLocale());

    return (
        <section
            className={`rounded-2xl border border-white/10 bg-black/20 p-5 sm:p-6 ${
                fullWidth
                    ? "w-full"
                    : ""
            }`}
        >
            <p className="text-xs font-bold uppercase tracking-[0.2em] text-pink-300">
                {t("permanentRecord")}
            </p>

            <h2 className="mt-2 text-2xl font-bold">
                {fullWidth
                    ? t("fullHistory")
                    : t("recentHistory")}
            </h2>

            <p className="mt-2 text-sm leading-6 text-white/50">
                {t("historyIntro")}
            </p>

            {errorMessage && (
                <div className="mt-5 rounded-xl border border-red-400/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">
                    {errorMessage}
                </div>
            )}

            <div className="mt-6 space-y-4">
                {history.length === 0 ? (
                    <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.025] px-5 py-10 text-center">
                        <p className="text-sm font-semibold text-white/60">
                            {t("noChangesRecorded")}
                        </p>

                        <p className="mt-2 text-xs text-white/35">
                            {t("historyEmptyBody")}
                        </p>
                    </div>
                ) : (
                    history.map((item) => (
                        <HistoryCard
                            key={item.id}
                            item={item}
                        />
                    ))
                )}
            </div>
        </section>
    );
}

function HistoryCard({
    item,
}: {
    item: NoteHistory;
}) {
    const t = useTranslations("admin.notes");
    const tRole = useTranslations("enums.role");
    const locale = toLocale(useLocale());

    return (
        <article className="rounded-2xl border border-white/10 bg-[#111115] p-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
                <span className="rounded-full border border-pink-400/25 bg-pink-500/10 px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-pink-200">
                    {t(`actions.${historyActionKey(item.action)}`)}
                </span>

                <span className="text-xs text-white/35">
                    {formatDateTime(item.createdAt, locale)}
                </span>
            </div>

            {item.fieldName && (
                <p className="mt-3 inline-block rounded bg-white/10 px-2 py-0.5 text-[11px] text-white/60">
                    {item.fieldName}
                </p>
            )}

            {item.summary && (
                <p className="mt-3 text-sm leading-6 text-white/80">
                    {item.summary}
                </p>
            )}

            <p className="mt-3 text-xs text-white/45">
                Por{" "}
                <span className="font-semibold text-white/70">
                    {item.editorName}
                </span>{" "}
                ·{" "}
                {tRole(item.editorRole)}
            </p>

            {item.originalBody &&
                item.updatedBody &&
                item.originalBody !==
                    item.updatedBody && (
                    <div className="mt-4 space-y-3">
                        <HistoryText
                            label={t("previousVersion")}
                            text={
                                item.originalBody
                            }
                            muted
                        />

                        <HistoryText
                            label={t("newVersion")}
                            text={
                                item.updatedBody
                            }
                        />
                    </div>
                )}

            {!item.originalBody &&
                item.updatedBody && (
                    <HistoryText
                        label={t("content")}
                        text={item.updatedBody}
                    />
                )}

            {item.originalBody &&
                !item.updatedBody && (
                    <HistoryText
                        label={t("recordedContent")}
                        text={item.originalBody}
                        muted
                    />
                )}
        </article>
    );
}

function HistoryText({
    label,
    text,
    muted = false,
}: {
    label: string;
    text: string;
    muted?: boolean;
}) {
    return (
        <div className="mt-3 rounded-xl border border-white/10 bg-black/20 p-3">
            <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-white/35">
                {label}
            </p>

            <p
                className={`mt-2 whitespace-pre-wrap break-words text-xs leading-5 ${
                    muted
                        ? "text-white/40 line-through decoration-white/20"
                        : "text-white/70"
                }`}
            >
                {text}
            </p>
        </div>
    );
}

function EditConfirmationModal({
    note,
    body,
    priority,
    isSaving,
    onBodyChange,
    onPriorityChange,
    onCancel,
    onConfirm,
}: {
    note: ModelNote;
    body: string;
    priority: NotePriority;
    isSaving: boolean;
    onBodyChange: (value: string) => void;
    onPriorityChange: (
        value: NotePriority,
    ) => void;
    onCancel: () => void;
    onConfirm: () => void;
}) {
    const t = useTranslations("admin.notes");
    const tCommon = useTranslations("common.actions");
    const tPriority = useTranslations("enums.notePriority");
    const locale = toLocale(useLocale());

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 px-4 py-8 backdrop-blur-sm">
            <div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl border border-pink-400/30 bg-[#111115] p-5 shadow-2xl sm:p-7">
                <p className="text-xs font-bold uppercase tracking-[0.2em] text-pink-300">
                    {t("confirmationRequired")}
                </p>

                <h2 className="mt-2 text-2xl font-bold">
                    {t("editThisNote")}
                </h2>

                <p className="mt-3 text-sm leading-6 text-white/55">
                    {t("editNotice")}
                </p>

                <div className="mt-6 rounded-2xl border border-white/10 bg-black/20 p-4">
                    <p className="text-xs font-bold uppercase tracking-[0.14em] text-white/35">
                        {t("currentVersion")}
                    </p>

                    <p className="mt-3 whitespace-pre-wrap break-words text-sm leading-6 text-white/55">
                        {note.body}
                    </p>
                </div>

                <label className="mt-5 block">
                    <span className="text-xs font-bold uppercase tracking-[0.14em] text-white/45">
                        {t("newVersion")}
                    </span>

                    <textarea
                        value={body}
                        onChange={(event) =>
                            onBodyChange(
                                event.target.value,
                            )
                        }
                        rows={7}
                        maxLength={5000}
                        className="mt-3 w-full resize-y rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm leading-6 text-white outline-none transition focus:border-pink-400/60"
                    />
                </label>

                <label className="mt-4 block">
                    <span className="text-xs font-bold uppercase tracking-[0.14em] text-white/45">
                        {t("priority")}
                    </span>

                    <select
                        value={priority}
                        onChange={(event) =>
                            onPriorityChange(
                                event.target
                                    .value as NotePriority,
                            )
                        }
                        className="mt-2 w-full rounded-xl border border-white/10 bg-[#08080a] px-4 py-3 text-sm text-white outline-none focus:border-pink-400/60"
                    >
                        {priorityOptions.map((option) => (
                                                <option key={option} value={option}>
                                                    {tPriority(option)}
                                                </option>
                                            ))}
                    </select>
                </label>

                <div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end">
                    <button
                        type="button"
                        onClick={onCancel}
                        disabled={isSaving}
                        className="rounded-xl border border-white/10 bg-white/5 px-5 py-3 text-sm font-semibold text-white/70 transition hover:bg-white/10 disabled:opacity-40"
                    >
                        {tCommon("cancel")}
                    </button>

                    <button
                        type="button"
                        onClick={onConfirm}
                        disabled={
                            isSaving ||
                            !body.trim()
                        }
                        className="rounded-xl bg-pink-500 px-5 py-3 text-sm font-bold text-white transition hover:bg-pink-400 disabled:cursor-not-allowed disabled:opacity-40"
                    >
                        {isSaving
                            ? tCommon("saving")
                            : t("confirmEdit")}
                    </button>
                </div>
            </div>
        </div>
    );
}

function ActionButton({
    children,
    disabled,
    onClick,
}: {
    children: React.ReactNode;
    disabled: boolean;
    onClick: () => void;
}) {
    return (
        <button
            type="button"
            disabled={disabled}
            onClick={onClick}
            className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-semibold text-white/60 transition hover:border-pink-400/30 hover:bg-pink-500/10 hover:text-pink-200 disabled:cursor-not-allowed disabled:opacity-35"
        >
            {children}
        </button>
    );
}

function EmptyNotes({
    showArchived,
}: {
    showArchived: boolean;
}) {
    const t = useTranslations("admin.notes");
    const locale = toLocale(useLocale());

    return (
        <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.025] px-5 py-12 text-center">
            <p className="text-base font-bold text-white/65">
                {showArchived
                    ? t("emptyArchivedTitle")
                    : t("emptyActiveTitle")}
            </p>

            <p className="mt-2 text-sm text-white/35">
                {showArchived
                    ? t("emptyTitle")
                    : t("emptyBody")}
            </p>
        </div>
    );
}

function LoadingSection({
    historyOnly,
}: {
    historyOnly: boolean;
}) {
    return (
        <section className="rounded-2xl border border-white/10 bg-black/20 p-8">
            <div className="animate-pulse">
                <div className="h-3 w-36 rounded bg-white/10" />
                <div className="mt-4 h-8 w-56 rounded bg-white/10" />

                <div
                    className={`mt-8 grid gap-5 ${
                        historyOnly
                            ? ""
                            : "xl:grid-cols-[minmax(0,1.6fr)_minmax(340px,0.8fr)]"
                    }`}
                >
                    <div className="h-80 rounded-2xl bg-white/5" />

                    {!historyOnly && (
                        <div className="h-80 rounded-2xl bg-white/5" />
                    )}
                </div>
            </div>
        </section>
    );
}

function normalizeNote(
    value: unknown,
    /**
     * Shown when the API returns no author name. UI copy, so it is passed in
     * rather than hardcoded — this is a plain helper and cannot hold a hook.
     */
    fallbackName: string,
): ModelNote | null {
    if (!isRecord(value)) {
        return null;
    }

    const id = readString(
        value.id,
    );

    const body = readString(
        value.body,
        value.content,
        value.note,
    );

    if (!id || !body) {
        return null;
    }

    return {
        id,
        modelId:
            readString(
                value.modelId,
                value.model_id,
            ) ?? "",
        body,
        priority: normalizePriority(
            readString(value.priority),
        ),
        pinned: readBoolean(
            value.pinned,
            value.is_pinned,
        ),
        archived: readBoolean(
            value.archived,
            value.is_archived,
        ),
        source:
            readString(value.source) ===
            "ledger"
                ? "ledger"
                : "manual",
        deletedAt:
            value.deleted_at === null
                ? null
                : readString(
                      value.deletedAt,
                      value.deleted_at,
                  ) ?? null,
        deletedByName:
            readString(
                value.deletedByName,
                value.deleted_by_name,
            ),
        createdContext:
            readString(
                value.createdContext,
                value.created_context,
            ),
        createdByName:
            readString(
                value.createdByName,
                value.created_by_name,
                value.authorName,
                value.author_name,
            ) ?? fallbackName,
        createdByRole:
            readString(
                value.createdByRole,
                value.created_by_role,
                value.authorRole,
                value.author_role,
            ) ?? "administrator",
        updatedByName:
            readString(
                value.updatedByName,
                value.updated_by_name,
            ),
        updatedByRole:
            readString(
                value.updatedByRole,
                value.updated_by_role,
            ),
        previousRepresentativeId:
            readString(
                value.previousRepresentativeId,
                value.previous_representative_id,
            ) ?? null,
        newRepresentativeId:
            readString(
                value.newRepresentativeId,
                value.new_representative_id,
            ) ?? null,
        createdAt:
            readString(
                value.createdAt,
                value.created_at,
            ) ??
            new Date().toISOString(),
        updatedAt:
            readString(
                value.updatedAt,
                value.updated_at,
            ) ??
            readString(
                value.createdAt,
                value.created_at,
            ) ??
            new Date().toISOString(),
    };
}

function normalizeHistory(
    value: unknown,
    /** See normalizeNote. */
    fallbackName: string,
): NoteHistory | null {
    if (!isRecord(value)) {
        return null;
    }

    const id = readString(
        value.id,
    );

    if (!id) {
        return null;
    }

    return {
        id,
        noteId: readString(
            value.noteId,
            value.note_id,
        ),
        action:
            readString(
                value.action,
                value.changeType,
                value.change_type,
            ) ?? "updated",
        fieldName: readString(
            value.fieldName,
            value.field_name,
        ),
        summary: readString(
            value.summary,
        ),
        originalBody: readString(
            value.originalBody,
            value.original_body,
            value.oldBody,
            value.old_body,
            value.previousBody,
            value.previous_body,
        ),
        updatedBody: readString(
            value.updatedBody,
            value.updated_body,
            value.newBody,
            value.new_body,
            value.body,
        ),
        editorName:
            readString(
                value.editorName,
                value.editor_name,
                value.createdByName,
                value.created_by_name,
            ) ?? fallbackName,
        editorRole:
            readString(
                value.editorRole,
                value.editor_role,
                value.createdByRole,
                value.created_by_role,
            ) ?? "administrator",
        createdAt:
            readString(
                value.createdAt,
                value.created_at,
            ) ??
            new Date().toISOString(),
    };
}

function isRecord(
    value: unknown,
): value is Record<string, unknown> {
    return (
        typeof value === "object" &&
        value !== null &&
        !Array.isArray(value)
    );
}

function readString(
    ...values: unknown[]
): string | null {
    for (const value of values) {
        if (
            typeof value === "string" &&
            value.trim()
        ) {
            return value;
        }
    }

    return null;
}

function readBoolean(
    ...values: unknown[]
): boolean {
    for (const value of values) {
        if (typeof value === "boolean") {
            return value;
        }

        if (value === 1 || value === "1") {
            return true;
        }

        if (value === 0 || value === "0") {
            return false;
        }
    }

    return false;
}

function normalizePriority(
    value: string | null,
): NotePriority {
    if (
        value === "important" ||
        value === "urgent"
    ) {
        return value;
    }

    return "normal";
}

function priorityConfig(
    priority: NotePriority,
) {
    // Colour only; the word comes from `enums.notePriority`.
    const configs: Record<NotePriority, { className: string }> = {
        normal: {
            className:
                "border-white/15 bg-white/5 text-white/50",
        },
        important: {
            className:
                "border-yellow-400/30 bg-yellow-500/10 text-yellow-200",
        },
        urgent: {
            className:
                "border-red-400/30 bg-red-500/10 text-red-200",
        },
    };

    return configs[priority];
}

/**
 * Maps an audit action to a key under `admin.notes.actions`.
 *
 * Returns the key rather than the sentence because this is a plain helper, not
 * a component — it cannot hold a hook, and threading a translator through it
 * would be worse than letting the caller translate.
 */
function historyActionKey(action: string): string {
    const normalized = action.toLowerCase();

    const keys: Record<string, string> = {
        created: "noteCreated",
        create: "noteCreated",
        edited: "noteEdited",
        edit: "noteEdited",
        updated: "noteUpdated",
        update: "noteUpdated",
        pinned: "notePinned",
        pin: "pinChanged",
        unpinned: "noteUnpinned",
        archived: "noteArchived",
        archive: "archiveChanged",
        restored: "noteRestored",
        restore: "noteRestored",
        // Account changes from `model_audit_history`, shown alongside notes.
        field_update: "fieldUpdate",
        status_change: "statusChange",
        proxy_update: "proxyUpdate",
        avatar_update: "avatarUpdate",
        checklist_update: "checklistUpdate",
        marketing_update: "marketingUpdate",
        onboarding_update: "onboardingUpdate",
        earnings_created: "earningsCreated",
        document_uploaded: "documentUploaded",
        note_deleted: "noteDeleted",
        model_deleted: "modelDeleted",
        model_created: "modelCreated",
        model_imported: "modelImported",
        model_applied: "modelApplied",
    };

    return keys[normalized] ?? "changeRecorded";
}

/** Audit timestamps: São Paulo time, in the reader's field order. */
function formatDateTime(value: string, locale: Locale) {
    const date = new Date(value);

    if (Number.isNaN(date.getTime())) {
        return value;
    }

    return formatLocalizedDateTime(date, locale);
}