-- =============================================================================
-- KARAY Models — restore column-level UPDATE for country_code / expenses_enabled
--
-- 20260801000000_earnings_ledger_and_fx.sql added models.country_code and
-- models.expenses_enabled and refreshed the column-level SELECT allowlist, but
-- not the UPDATE one. Table-wide UPDATE on public.models is revoked
-- (20260729000000_model_proxy_details.sql), so `authenticated` could read both
-- columns and write neither: the country dropdown and the
-- "Lançamentos de despesas e empréstimos" checkbox both failed with
-- `permission denied for column`, which left every model stuck with
-- expenses_enabled = false and the ledger invisible everywhere.
--
-- Both allowlists are rebuilt here from a single restricted list so they
-- cannot drift apart again. Two different exclusion sets, deliberately:
--   * SELECT excludes the marketing + proxy columns AND latest_note_summary
--     (note content — 20260731000000);
--   * UPDATE excludes only the marketing + proxy columns. latest_note_summary
--     must stay updatable: updateLatestNoteSummary in the notes route writes
--     it with a bare UPDATE.
--
-- REMINDER for future migrations: any new column on public.models is invisible
-- and unwritable to `authenticated` until this do-block is re-run.
-- =============================================================================
do $$
declare
  restricted_write text[] := array[
    'instagram_marketing',
    'twitter_marketing',
    'proxy_ip',
    'proxy_company',
    'proxy_company_other',
    'proxy_country'
  ];
  restricted_read text[] := restricted_write || array['latest_note_summary'];
  select_cols text;
  update_cols text;
begin
  select string_agg(quote_ident(column_name), ', ' order by ordinal_position)
    into select_cols
    from information_schema.columns
   where table_schema = 'public'
     and table_name = 'models'
     and not (column_name = any (restricted_read));

  -- Generated / identity columns cannot be granted for UPDATE. models.model_number
  -- is `generated by default as identity` and IS updatable, so it is granted
  -- separately below (20260729010000 had to restore it once already).
  select string_agg(quote_ident(column_name), ', ' order by ordinal_position)
    into update_cols
    from information_schema.columns
   where table_schema = 'public'
     and table_name = 'models'
     and not (column_name = any (restricted_write))
     and is_generated = 'NEVER'
     and is_identity = 'NO';

  if select_cols is null or update_cols is null then
    raise exception 'models table introspection returned no columns — aborting to avoid locking out all access';
  end if;

  execute 'revoke select on public.models from authenticated';
  execute format('grant select (%s) on public.models to authenticated', select_cols);

  execute 'revoke update on public.models from authenticated';
  execute format('grant update (%s) on public.models to authenticated', update_cols);
end $$;

grant update (model_number) on public.models to authenticated;

-- Fail loudly here rather than silently in the UI six weeks from now.
do $$
begin
  if not has_column_privilege('authenticated', 'public.models', 'expenses_enabled', 'UPDATE')
     or not has_column_privilege('authenticated', 'public.models', 'country_code', 'UPDATE')
     or not has_column_privilege('authenticated', 'public.models', 'latest_note_summary', 'UPDATE')
     or has_column_privilege('authenticated', 'public.models', 'latest_note_summary', 'SELECT')
     or has_column_privilege('authenticated', 'public.models', 'proxy_ip', 'SELECT')
  then
    raise exception 'models column grants are not in the expected state after this migration';
  end if;
end $$;
