-- =============================================================================
-- KARAY Models — restore UPDATE on models.model_number for `authenticated`
--
-- 20260729000000_model_proxy_details.sql introduced a column-level UPDATE
-- allowlist and defensively skipped identity columns while re-granting.
-- models.model_number is `generated by default as identity`, which IS
-- updatable, and `authenticated` could update it before that migration — so
-- the skip silently narrowed an existing privilege. Restore it.
-- =============================================================================
grant update (model_number) on public.models to authenticated;
